version: 2
machine:
jobs:
  build:
    docker:
      - image: ubuntu:xenial-20161213
        environment:
          OSF_PROJECT: https://files.osf.io/v1/resources/fvuh8/providers/osfstorage
          DS005_URL: /57f32a429ad5a101f977eb75
          DS005_FS_URL: /58fe59eb594d900250960180
          DS054_URL: /57f32c22594d9001ef91bf9e
    steps:
      - checkout
      - run:
          name: install pre reqs
          command: |
            apt-get update && apt-get -y install python3 python3-dev python3-pip cython build-essential curl wget git

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - restore_cache:
          keys:
            - fmriprep-data
      - run:
          name: pre
          command: |
            mkdir -p $HOME/data
            mkdir -p $HOME/ds005/out/
            mkdir -p $HOME/ds054
            mkdir -p $HOME/docs
            # Download test data
            if [[ ! -d $HOME/data/ds005 ]]; then wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q -O ds005_downsampled.tar.gz $OSF_PROJECT$DS005_URL && tar xzf ds005_downsampled.tar.gz -C $HOME/data/; fi
            if [[ ! -d $HOME/data/ds054 ]]; then wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q -O ds054_downsampled.tar.gz $OSF_PROJECT$DS054_URL && tar xzf ds054_downsampled.tar.gz -C $HOME/data/; fi
            if [[ ! -d $HOME/data/freesurfer ]]; then wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q -O ds005_derivatives_freesurfer.tar.gz $OSF_PROJECT$DS005_FS_URL && tar xzf ds005_derivatives_freesurfer.tar.gz -C $HOME/data/; fi
            cp -al $HOME/data/freesurfer $HOME/ds005/out/freesurfer
            printf "[execution]\nstop_on_first_crash = true\nremove_unnecessary_outputs = false" > $HOME/nipype.cfg
            # Setup dependencies
            pip3 install future numpy
            # Verify we can run setup.py
            python3 setup.py --help
            python3 wrapper/setup.py --help
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum  "Dockerfile" }}
          paths:
            - /caches/docker.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/docker.tar | true
          no_output_timeout: 1200
      - run:
          name: Build docker image
          command: |
            sed -i -E "s/(__version__ = )'[A-Za-z0-9.-]+'/\1'$CIRCLE_TAG'/" fmriprep/info.py
            sed -i -E "s/(__version__ = )'[A-Za-z0-9.-]+'/\1'$CIRCLE_TAG'/" wrapper/fmriprep_docker.py
            docker pull poldracklab/fmriprep:latest || true
            docker build --cache-from=poldracklab/fmriprep --rm=false -t poldracklab/fmriprep:latest --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg VERSION=${CIRCLE_TAG:-latest} . 
            pip3 install --upgrade wrapper/
          no_output_timeout: 1200
          timeout: 21600
      - run:
          name: Save docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/docker.tar poldracklab/fmriprep:latest
          no_output_timeout: 1200
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "Dockerfile" }}-{{ epoch }}
          paths:
            - /caches/docker.tar
      - restore_cache:
          key:  ds054-workdir-{{ .Branch }}
          paths:
            - /root/ds0054/out
      - run:
          command: |
            docker create -v /out -v /scratch -v /root/.nipype/ -v /data --name data alpine:3.4 /bin/true
            docker cp /root/data/ds054/ data:/data
            docker cp /root/nipype.cfg data:/root/.nipype/
      - run:
          name: ds054 tests
          command: |
            docker run -it --volumes-from=data poldracklab/fmriprep:latest /data/ds054 /out participant --no-freesurfer --debug --write-graph --force-syn -w /scratch
          no_output_timeout: 3600
      - run:
          command: |
            docker cp data:/out /root/ds0054/
            docker cp data:/scratch /root/ds0054
            find ~/ds054/scratch -not -name "*.svg" -not -name "*.html" -not -name "*.svg" -not -name "*.rst" -type f -delete
      - save_cache:
          key: ds054-workdir-{{ .Branch }}-{{ epoch }}
          paths:
            - /root/ds0054/out
      - run:
          name: unittests
          command:
            docker run -ti --rm=false --entrypoint="python" poldracklab/fmriprep:latest -m unittest discover test
